name: file update constant.dart
on: 
  push:
  
# the build will run on code push in a branch in which this file is present. 

jobs:
  build:
     runs-on: ubuntu-latest
     
     # permissions given for code push in repository.
     
     permissions:
      contents: write
      pull-requests: write
     steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}  
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Change something
        run: | 
        
         # delete the line containing below options.
         
         #while first adding this cript make sure constant.dart file contains line with below text otherwise build fails.
         
         sed -i '/String baseUrl()/d' ./smart_node/lib/helper/constants.dart
          sed -i '/String v2BaseUrl()/d' ./smart_node/lib/helper/constants.dart
         sed -i '/apiVersion/d' ./smart_node/lib/helper/constants.dart
          sed -i '/build_run_number/d' ./smart_node/lib/helper/constants.dart
         
      - name: Update String baseUrl()
        run: |          
          if [[ ${GITHUB_REF#refs/heads/} == "app-release" ]]; then
           echo "String baseUrl() => SharedPreferenceManager.isLocalUrl()  ? 'http://10.10.10.102:5000/api/\${apiVersion[0]}': 'https://api.smartnode.in/api/\${apiVersion[0]}';" >> smart_node/lib/helper/constants.dart       
          else
            echo "String baseUrl() => SharedPreferenceManager.isLocalUrl() ? 'http://10.10.10.102:5000/api/\${apiVersion[0]}': 'https://test.api.smartnode.in/api/\${apiVersion[0]}';" >> smart_node/lib/helper/constants.dart
          fi
          
          #add this line in code for selection of correct URL while building according to branch name present.
      - name: Update String v2BaseUrl()
        run: |          
          if [[ ${GITHUB_REF#refs/heads/} == "app-release" ]]; then
           echo " String v2BaseUrl() => SharedPreferenceManager.isLocalUrl()   ? 'http://10.10.10.102:5000/api/${apiVersion[1]}' : 'https://api.smartnode.in/api/${apiVersion[1]}';" >> smart_node/lib/helper/constants.dart       
          else
            echo "String v2BaseUrl() => SharedPreferenceManager.isLocalUrl() ? 'http://10.10.10.102:5000/api/\${apiVersion[1]}': 'https://test.api.smartnode.in/api/\${apiVersion[1]}';" >> smart_node/lib/helper/constants.dart
          fi
          
          #add this line in code for selection of correct URL while building according to branch name present.
          
      - name: Output Run Number
        run: echo "//build_run_number=${{ github.run_number }}" >> smart_node/lib/helper/constants.dart
        
        #run number is required otherwise build will fail.
        
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add smart_node/lib/helper/constants.dart
          git commit -m "Update smart_node/lib/helper/constants.dart file with branch name [skip ci]"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }} 
