name: Deployment
env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
on:   
   pull_request:
   push:
     branches:
       - echo ${{ env.BRANCH_NAME }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
      
