name: Pull request labeler
on: 
  push: 
  pull_request:
  
jobs:
  build:
     runs-on: ubuntu-latest
     permissions:
      contents: write
      pull-requests: write
     steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}  
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Change something
        run: |   
         sed -i '/String baseUrl()/d' ./smart_node/lib/helper/constants.dart
         sed -i '/apiVersion/d' ./smart_node/lib/helper/constants.dart
         
    #  - name: Update .env file
     #   run: |
     #     echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> smart_node/lib/helper/constants.dart
      #    cat .env   
      - name: Update .env file
        run: |          
          if [[ ${GITHUB_REF#refs/heads/} == "appurlselector" ]]; then
           echo "String baseUrl() => SharedPreferenceManager.isLocalUrl() ? 'http://10.10.10.102:5000/api/${apiVersion[0]}': 'https://api.smartnode.in/api/${apiVersion[0]}';" >> smart_node/lib/helper/constants.dart       
          else
            echo "URL=mongodbsupportserverrelease" >> smart_node/lib/helper/constants.dart 
          fi
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add smart_node/lib/helper/constants.dart
          git commit -m "Update smart_node/lib/helper/constants.dart file with branch name [skip ci]"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }} 
